- name: Check if bootstrap is needed
  raw: stat $HOME/.bootstrapped >&/dev/null && echo 1 || echo 0
  register: need_bootstrap
  changed_when: need_bootstrap.stdout[0] == "0"

- name: Run bootstrap.sh
  script: bootstrap.sh
  when: need_bootstrap.changed

- name: Check if we need to install pip
  shell:
    "{{ansible_python_interpreter}} -m pip --version >&/dev/null
    && echo 1 || echo 0"
  register: need_pip
  changed_when: need_pip.stdout[0] == "0"

- block:

    - name: Copy get-pip.py
      copy: src=get-pip.py dest=~/get-pip.py

    - name: Install pip
      shell: "{{ansible_python_interpreter}} ~/get-pip.py"

    - name: Remove get-pip.py
      file: path=~/get-pip.py state=absent

    - name: Install pip launcher
      copy: src=runner dest=~/bin/pip mode=0755

  when: need_pip.changed

